{{- if .Values.composition.enabled }}
apiVersion: network.aws.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: {{ .Values.composition.claimName | quote }}
spec:
  compositionRef:
    name: {{ .Values.composition.name | quote }}
  parameters:
    region: {{ .Values.aws.region | quote }}
    providerConfigName: {{ .Values.composition.providerConfigName | quote }}
    vpc:
      cidrBlock: {{ .Values.composition.vpc.cidrBlock | quote }}
      enableDnsSupport: {{ .Values.composition.vpc.enableDnsSupport }}
      enableDnsHostnames: {{ .Values.composition.vpc.enableDnsHostnames }}
      tags:
{{- range .Values.composition.vpc.tags }}
        - key: {{ .key | quote }}
          value: {{ .value | quote }}
{{- end }}
    natGateway:
      enabled: {{ .Values.composition.natGateway.enabled }}
      publicSubnetIndex: {{ .Values.composition.natGateway.publicSubnetIndex }}
    publicSubnets:
{{- range .Values.composition.publicSubnets }}
      - name: {{ .name | quote }}
        cidrBlock: {{ .cidrBlock | quote }}
        availabilityZone: {{ .availabilityZone | quote }}
        tags:
{{- range .tags }}
          - key: {{ .key | quote }}
            value: {{ .value | quote }}
{{- end }}
{{- end }}
    privateSubnets:
{{- range .Values.composition.privateSubnets }}
      - name: {{ .name | quote }}
        cidrBlock: {{ .cidrBlock | quote }}
        availabilityZone: {{ .availabilityZone | quote }}
        tags:
{{- range .tags }}
          - key: {{ .key | quote }}
            value: {{ .value | quote }}
{{- end }}
{{- end }}
{{- end }}

